# -*- coding: utf-8 -*-
"""YOLO tracking and predictive modeling.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DyGHqB8SGxehqvYlqEe_uBUijqor78s-

#Task 4
"""

!pip install ultralytics -q

"""# Uploading the video"""

from google.colab import files
uploaded = files.upload()  # upload motorway.mp4 here

"""# Imports the libraries"""

import cv2
from ultralytics import YOLO
from collections import defaultdict

"""# Load the model"""

model = YOLO("yolov8m.pt")  # medium model, much better detection

from ultralytics import YOLO
model = YOLO("yolov8m.pt")

"""# Run Tracking+Counting"""

from ultralytics import YOLO
model = YOLO("yolov8m.pt") # Re-initialize the YOLO model

VIDEO_PATH  = "motorway.mp4"
OUTPUT_PATH = "output_counted.mp4"

# FIX 1: Use a LIST not a set — guarantees stable display order on every frame
TARGET_CLASSES = ["car", "motorcycle", "bus", "truck"]

cap    = cv2.VideoCapture(VIDEO_PATH)
width  = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps    = int(cap.get(cv2.CAP_PROP_FPS))

out = cv2.VideoWriter(OUTPUT_PATH, cv2.VideoWriter_fourcc(*"mp4v"), fps, (width, height))

tracked_ids = defaultdict(set)   # unique track_ids seen per class

# FIX 2: Per-class sequential numbering so bounding-box label shows
#         'car #3' meaning '3rd unique car', NOT the raw ByteTrack ID
vehicle_seq      = defaultdict(dict)  # class -> {track_id: seq_number}
vehicle_counters = defaultdict(int)   # class -> how many unique vehicles seen

while True:
    ret, frame = cap.read()
    if not ret:
        break

    results = model.track(frame, persist=True, verbose=False, conf=0.3,
                          iou=0.5, tracker="bytetrack.yaml")[0]

    if results.boxes is not None and results.boxes.id is not None:

        for box, track_id, cls_id in zip(
            results.boxes.xyxy,
            results.boxes.id,
            results.boxes.cls
        ):
            class_name = model.names[int(cls_id)]
            if class_name in TARGET_CLASSES:
                tid = int(track_id)
                tracked_ids[class_name].add(tid)

                # Assign a sequential number the first time this track_id appears
                if tid not in vehicle_seq[class_name]:
                    vehicle_counters[class_name] += 1
                    vehicle_seq[class_name][tid] = vehicle_counters[class_name]

                # FIX 2: use sequential number, not raw tracker ID
                display_num = vehicle_seq[class_name][tid]
                x1, y1, x2, y2 = map(int, box)
                label = f"{class_name} #{display_num}"
                cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)
                cv2.putText(frame, label, (x1, y1 - 8),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

    # Draw live counts — FIX 1: list keeps order stable every frame
    y_offset = 30
    for cls_name in TARGET_CLASSES:
        count = len(tracked_ids[cls_name])
        text  = f"{cls_name}: {count}"
        cv2.putText(frame, text, (10, y_offset),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 0, 255), 2)
        y_offset += 30

    out.write(frame)

cap.release()
out.release()
print("Done!")

"""# Print final counts"""

print("\n===== FINAL VEHICLE COUNTS (CALCULATED) =====")
for cls_name, ids in tracked_ids.items():
    print(f"  {cls_name.upper():<12}: {len(ids)}")
print("==========================================")

"""# Download the Final output"""

from IPython.display import Video, display
display(Video("output_counted.mp4", embed=True))

"""# Task 2

# Install and import libraries
"""

!pip install -q scikit-learn pandas matplotlib seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import r2_score, mean_squared_error

"""# Upload the CSV"""

from google.colab import files
uploaded = files.upload()  # upload insurance.csv

"""# Load And Preview"""

df = pd.read_csv("insurance.csv")
print(df.shape)
print(df.head())
print(df.info())
print(df.describe())
print("\nMissing values:\n", df.isnull().sum())

"""# EDA"""

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Age vs Charges
axes[0].scatter(df['age'], df['charges'], alpha=0.5, color='steelblue')
axes[0].set_title('Age vs Charges')
axes[0].set_xlabel('Age')
axes[0].set_ylabel('Charges')

# BMI vs Charges
axes[1].scatter(df['bmi'], df['charges'], alpha=0.5, color='green')
axes[1].set_title('BMI vs Charges')
axes[1].set_xlabel('BMI')

# Smoking vs Charges
sns.boxplot(x='smoker', y='charges', data=df, ax=axes[2], palette='Set2')
axes[2].set_title('Smoker vs Charges')

plt.tight_layout()
plt.show()

# Correlation heatmap
plt.figure(figsize=(8, 5))
sns.heatmap(df.select_dtypes(include=np.number).corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

"""# Preprocessing"""

df_enc = df.copy()

# Encode categorical columns
le = LabelEncoder()
for col in ['sex', 'smoker', 'region']:
    df_enc[col] = le.fit_transform(df_enc[col])

# Features & target
X = df_enc.drop('charges', axis=1)
y = df_enc['charges']

# Scale
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

print("Train size:", X_train.shape)
print("Test size:", X_test.shape)

"""# Train & Compare Regressors"""

models = {
    "Linear Regression":     LinearRegression(),
    "Decision Tree":         DecisionTreeRegressor(random_state=42),
    "Random Forest":         RandomForestRegressor(random_state=42),
    "Gradient Boosting":     GradientBoostingRegressor(random_state=42),
}

results = []

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    r2   = r2_score(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    results.append({"Model": name, "R²": round(r2, 4), "RMSE": round(rmse, 2)})
    print(f"{name:25s} | R²: {r2:.4f} | RMSE: {rmse:.2f}")

results_df = pd.DataFrame(results).sort_values("R²", ascending=False)
print("\n", results_df)

"""# GridSearchCV on Best Model (Gradient Boosting)

"""

from sklearn.ensemble import GradientBoostingRegressor

# GradientBoosting was the best model (R²=0.8776), so we tune IT
param_grid = {
    'n_estimators':  [100, 200],
    'learning_rate': [0.05, 0.1],
    'max_depth':     [3, 4, 5],
}

grid_search = GridSearchCV(
    GradientBoostingRegressor(random_state=42),
    param_grid,
    cv=5,
    scoring='r2',
    n_jobs=-1,
    verbose=1
)

grid_search.fit(X_train, y_train)

print("Best Params:", grid_search.best_params_)

best_model   = grid_search.best_estimator_
y_pred_best  = best_model.predict(X_test)

r2_best   = r2_score(y_test, y_pred_best)
rmse_best = np.sqrt(mean_squared_error(y_test, y_pred_best))

print(f"\nAfter Tuning → R²: {r2_best:.4f} | RMSE: {rmse_best:.2f}")

"""# Final Summary Plot"""

models_names  = results_df["Model"].tolist()
r2_scores     = results_df["R²"].tolist()
rmse_scores   = results_df["RMSE"].tolist()

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].barh(models_names, r2_scores, color='steelblue')
axes[0].set_title('R² Score (higher is better)')
axes[0].set_xlim(0, 1)

axes[1].barh(models_names, rmse_scores, color='salmon')
axes[1].set_title('RMSE (lower is better)')

plt.tight_layout()
plt.show()

"""# Task 3"""

# Q3 - Total Number of Parameters in the DNN
# DNN on ASL images 224x224 (RGB), hidden layers 128/256/512, output 26, bias = 0

# Step 1: Flatten the input image (fully-connected DNN)
H, W, C = 224, 224, 3                 # height, width, channels (RGB)
input_neurons = H * W * C             # 224 x 224 x 3
print(f"Step 1 - Flattened input = {H} x {W} x {C} = {input_neurons:,} neurons\n")

# Step 2: Network architecture (neurons per layer, in order)
architecture = [input_neurons, 128, 256, 512, 26]
names = ["Input", "Hidden 1", "Hidden 2", "Hidden 3", "Output"]

# Step 3 & 4: Bias = 0, so count ONLY the weights
# weights = (neurons in previous layer) x (neurons in current layer)
total_params = 0
print(f"{'Connection':22s}{'Calculation':26s}{'Parameters':>14s}")
print("-" * 62)
for i in range(len(architecture) - 1):
    prev, curr = architecture[i], architecture[i + 1]
    weights = prev * curr
    total_params += weights
    conn = f"{names[i]} -> {names[i+1]}"
    calc = f"{prev:,} x {curr:,}"
    print(f"{conn:22s}{calc:26s}{weights:>14,}")
print("-" * 62)

# Final answer
print(f"\nTotal number of parameters in the DNN = {total_params:,}")

"""## Q3 — Total Number of Parameters in the DNN

**Step 1 — Flatten the input:** 224 × 224 × 3 = 150,528 input neurons.
**Step 2 — Architecture:** 150,528 → 128 → 256 → 512 → 26.
**Step 3 — Bias = 0**, so count weights only: weights = (prev neurons) × (curr neurons).
**Result:** 19,267,584 + 32,768 + 131,072 + 13,312 = **19,444,736 parameters**.

------------------------------------------------

**Question no 1**

**(a) What is Overfitting, and How Can You Avoid It?**

Overfitting occurs when a model learns the training data too well and even memorizes noise and random details. Because of that, it performs great on training data but fails badly on new/unseen data.

Ways to avoid it:

1.	Use more training data
2.	Apply regularization (L1/L2)
3.	Use cross-validation
4.	Simplify the model (fewer features or layers)
5.	Use dropout (in neural networks)

**(b) What is the Bias-Variance Tradeoff?**

Basically, it's the balance between two types of errors a model can make:

1.	Bias = when the model is too simple and misses patterns (underfitting)
2.	Variance = when the model is too complex and reacts to noise (overfitting)

A good model has low bias AND low variance, but reducing one usually increases the other. That's the tradeoff. We try to find the sweet spot.

**(c) When Will You Use Classification over Regression?**

We use Classification when the output is a category (like yes/no, spam/not spam, dog/cat). We use Regression when we want to predict a numerical value (such as price, temperature, or salary).

Use Classification when:

1.	Predicting if an email is spam or not
2.	Identifying if a tumor is malignant or benign
3.	Predicting which class a student belongs to (pass/fail)

**(d) What is Cross-Validation?**

Cross-validation is a technique used to test how well a model performs on unseen data. Instead of splitting data just once, we split it multiple times and test on each part.

The most common type is K-Fold Cross-Validation, in which the data is split into K equal folds. The model trains on K-1 parts and tests on the remaining one. This is repeated K times, so every part gets a chance to be the test set. The final score is the average of all runs.

It gives a more reliable performance estimate than a single train/test split.





**(e) What is the F1 Score?**

Calculate F1 from the Confusion Matrix.
F1 Score is the harmonic mean of Precision and Recall. It's useful when we have an imbalanced dataset (like more negatives than positives). A high F1 means the model is doing well on both precision and recall.

From the confusion matrix:

1.	TP (True Positive) = 52
2.	FP (False Positive) = 12
3.	FN (False Negative) = 8
4.	TN (True Negative) = 119

Precision = TP / (TP + FP) = 52 / (52 + 12) = 52 / 64 = 0.8125
Recall = TP / (TP + FN) = 52 / (52 + 8) = 52 / 60 = 0.8667
F1 = 2 x (Precision x Recall) / (Precision + Recall)
F1 = 2 x (0.8125 x 0.8667) / (0.8125 + 0.8667)
F1 = 2 x 0.7042 / 1.6792 = 1.4083 / 1.6792

F1 Score = 0.8388 (approx. 0.84)
So, the F1 score is around 0.84, which means the model is performing pretty well overall.
"""

