# -*- coding: utf-8 -*-
"""Aviation_Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QJzfgJxvaCBajJMyyFQhg3cMaKzO4d0T

# ✈️ Aviation Safety — Live Interactive Dashboard
### Simply upload the CSV — everything else is automatic

**Required file:** `raw_airplane_crashes_1908_2009.csv`  
**There are 3 cells — Run them from top to bottom. The dashboard will appear directly here.**

## Cell 1 — Upload CSV
"""

from google.colab import files
print("CSV file (raw_airplane_crashes_1908_2009.csv)")
uploaded = files.upload()
CSV_PATH = list(uploaded.keys())[0]
print(f"✅  {CSV_PATH}")

from google.colab import drive
drive.mount('/content/drive')

"""## Cell 2 — Install Libraries"""

!pip install -q ipywidgets plotly pandas numpy
from google.colab import output
output.enable_custom_widget_manager()
print("✅ Ready!")

"""## Cell 3 — ✅ Dashboard LIVE (Preprocess + Render)"""

import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import ipywidgets as widgets
from IPython.display import display, HTML

df = pd.read_csv(CSV_PATH)
df.columns = [c.strip() for c in df.columns]

df["Date"]        = pd.to_datetime(df["Date"], errors="coerce", format="%m/%d/%Y")
df                = df.dropna(subset=["Date"]).copy()
df["Year"]        = df["Date"].dt.year.astype(int)
df["Month"]       = df["Date"].dt.month
df["MonthName"]   = df["Date"].dt.month_name()
df["Decade"]      = (df["Year"] // 10) * 10
df["DecadeLabel"] = df["Decade"].astype(str) + "s"

for col in ["Aboard", "Fatalities", "Ground"]:
    df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0)
df["Survivors"]    = (df["Aboard"] - df["Fatalities"]).clip(lower=0)
df["FatalityRate"] = np.where(df["Aboard"] > 0, df["Fatalities"] / df["Aboard"], 0)
df["TotalDeaths"]  = df["Fatalities"] + df["Ground"]

df["Location"] = df["Location"].fillna("Unknown")
US_STATES = {
    'Alabama','Alaska','Arizona','Arkansas','California','Colorado','Connecticut',
    'Delaware','Florida','Georgia','Hawaii','Idaho','Illinois','Indiana','Iowa',
    'Kansas','Kentucky','Louisiana','Maine','Maryland','Massachusetts','Michigan',
    'Minnesota','Mississippi','Missouri','Montana','Nebraska','Nevada',
    'New Hampshire','New Jersey','New Mexico','New York','North Carolina',
    'North Dakota','Ohio','Oklahoma','Oregon','Pennsylvania','Rhode Island',
    'South Carolina','South Dakota','Tennessee','Texas','Utah','Vermont',
    'Virginia','Washington','West Virginia','Wisconsin','Wyoming','Washington DC','D.C.'
}
def extract_country(loc):
    c = str(loc).split(",")[-1].strip()
    if c in US_STATES or "USA" in str(loc).upper(): return "USA"
    if c == "USSR": return "Russia"
    if c == "UK":   return "United Kingdom"
    return c
df["Country"] = df["Location"].apply(extract_country)

def get_mfg(text):
    t = str(text).upper()
    for n in ["BOEING","DOUGLAS","AIRBUS","CESSNA","LOCKHEED","ANTONOV","TUPOLEV"]:
        if n in t: return n.title()
    return "De Havilland" if "DE HAVILLAND" in t else "Other"
df["Manufacturer"] = df["Type"].apply(get_mfg)

def get_op_type(op):
    op = str(op).upper()
    if any(k in op for k in ["MILITARY","AIR FORCE","NAVY","ARMY","USAF","RAF"]): return "Military"
    if any(k in op for k in ["PRIVATE","CHARTER","PERSONAL"]):                      return "Private"
    return "Commercial"
df["OperatorType"] = df["Operator"].fillna("Unknown").apply(get_op_type)

def get_cause(s):
    s = str(s).upper()
    if any(k in s for k in ["ENGINE","MECHANICAL","GEAR","STRUCTURAL","PROPELLER"]): return "Mechanical Failure"
    if any(k in s for k in ["WEATHER","STORM","WIND","FOG","ICE","SNOW","LIGHTNING"]):  return "Weather Related"
    if any(k in s for k in ["PILOT ERROR","HUMAN ERROR","CONTROL","NAVIGATION"]):        return "Pilot Error"
    if any(k in s for k in ["TERRORIST","ATTACK","BOMB","HIJACKING","WAR"]):             return "Terrorism/Sabotage"
    if any(k in s for k in ["FIRE","EXPLOSION"]):                                          return "Fire/Explosion"
    if any(k in s for k in ["MAINTENANCE","INSPECTION"]):                                 return "Maintenance Issue"
    return "Other/Unknown"
df["CauseCategory"] = df["Summary"].apply(get_cause)
print(f"✅ Data processed: {len(df):,} records ({df.Year.min()}–{df.Year.max()})")

BG      = "#0b1220"
PANEL   = "#111a2e"
ACCENT  = "#22d3ee"
WARN    = "#f97316"
TXT     = "#e2e8f0"
MUTED   = "#94a3b8"
PLOT_KW = dict(template="plotly_dark",
               paper_bgcolor="rgba(0,0,0,0)",
               plot_bgcolor="rgba(0,0,0,0)",
               font=dict(color=TXT, size=11),
               margin=dict(l=40, r=40, t=50, b=30)) # Increased margins for more space

display(HTML(f"""
<style>
  .dash-wrap  {{ background:{BG}; padding:20px; border-radius:12px; font-family:'Segoe UI',sans-serif; }}
  .dash-title {{ color:#f8fafc; font-size:26px; font-weight:700; margin:0 0 4px 0; }}
  .dash-sub   {{ color:{MUTED}; font-size:13px; margin:0 0 20px 0; }}
  .kpi-row    {{ display:flex; gap:12px; flex-wrap:wrap; margin-bottom:18px; }}
  .kpi-card   {{ background:linear-gradient(180deg,#152040,#0d162c);
                 border:1px solid #25324d; border-radius:12px;
                 padding:14px 20px; flex:1; min-width:130px; }}
  .kpi-label  {{ color:{MUTED}; font-size:10px; text-transform:uppercase;
                 letter-spacing:.08em; margin-bottom:6px; }}
  .kpi-value  {{ color:{ACCENT}; font-size:24px; font-weight:700; }}
  .kpi-warn   {{ color:{WARN}; }}
  .section    {{ color:#cbd5e1; font-size:13px; font-weight:600;
                 text-transform:uppercase; letter-spacing:.06em;
                 margin:18px 0 8px 0; border-bottom:1px solid #1f2a44;
                 padding-bottom:6px; }}
  .filter-row {{ background:{PANEL}; border:1px solid #1f2a44; border-radius:10px;
                 padding:14px 18px; margin-bottom:16px; }}
  .filter-lbl {{ color:{MUTED}; font-size:11px; margin-bottom:4px; }}
</style>
"""))

yr_min, yr_max = int(df.Year.min()), int(df.Year.max())

w_year = widgets.IntRangeSlider(
    value=[yr_min, yr_max], min=yr_min, max=yr_max, step=1,
    description="📅 Year:", continuous_update=False,
    layout=widgets.Layout(width="98%"),
    style={"description_width": "80px",
           "handle_color": ACCENT}
)
w_op = widgets.SelectMultiple(
    options=sorted(df.OperatorType.unique()),
    value=list(df.OperatorType.unique()),
    description="✈️ Operator:",
    layout=widgets.Layout(height="70px", width="220px"),
    style={"description_width": "80px"}
)
w_cause = widgets.SelectMultiple(
    options=sorted(df.CauseCategory.unique()),
    value=list(df.CauseCategory.unique()),
    description="⚠️ Cause:",
    layout=widgets.Layout(height="70px", width="260px"),
    style={"description_width": "70px"}
)
w_mfg = widgets.SelectMultiple(
    options=sorted(df.Manufacturer.unique()),
    value=list(df.Manufacturer.unique()),
    description="🔧 Maker:",
    layout=widgets.Layout(height="70px", width="200px"),
    style={"description_width": "70px"}
)

# Output areas
out_kpi    = widgets.Output()
out_trend  = widgets.Output()
out_mid    = widgets.Output()
out_geo    = widgets.Output()
out_season = widgets.Output()
out_table  = widgets.Output()

def render(change=None):
    yr_lo, yr_hi = w_year.value
    f = df[
        df.Year.between(yr_lo, yr_hi) &
        df.OperatorType.isin(list(w_op.value)) &
        df.CauseCategory.isin(list(w_cause.value)) &
        df.Manufacturer.isin(list(w_mfg.value))
    ]

    total_acc  = len(f)
    total_fat  = int(f.Fatalities.sum())
    total_ab   = int(f.Aboard.sum())
    surv       = 100*(total_ab - total_fat)/max(total_ab,1)
    worst_yr   = int(f.groupby("Year")["Fatalities"].sum().idxmax()) if total_acc else "—"
    top_ctry   = f.Country.value_counts().idxmax() if total_acc else "—"
    top_cause  = f.CauseCategory.value_counts().idxmax() if total_acc else "—"

    # KPIs
    with out_kpi:
        out_kpi.clear_output(wait=True)
        display(HTML(f"""
        <div class="kpi-row">
          <div class="kpi-card"><div class="kpi-label">Total Accidents</div>
            <div class="kpi-value kpi-warn">{total_acc:,}</div></div>
          <div class="kpi-card"><div class="kpi-label">Total Fatalities</div>
            <div class="kpi-value kpi-warn">{total_fat:,}</div></div>
          <div class="kpi-card"><div class="kpi-label">Total Aboard</div>
            <div class="kpi-value">{total_ab:,}</div></div>
          <div class="kpi-card"><div class="kpi-label">Survival Rate</div>
            <div class="kpi-value">{surv:.1f}%</div></div>
          <div class="kpi-card"><div class="kpi-label">Worst Year</div>
            <div class="kpi-value kpi-warn">{worst_yr}</div></div>
          <div class="kpi-card"><div class="kpi-label">Most Affected</div>
            <div class="kpi-value" style="font-size:16px">{top_ctry}</div></div>
          <div class="kpi-card"><div class="kpi-label">Leading Cause</div>
            <div class="kpi-value kpi-warn" style="font-size:14px">{top_cause}</div></div>
        </div>
        """))

    if total_acc == 0:
        for o in [out_trend, out_mid, out_geo, out_season, out_table]:
            with o:
                o.clear_output(wait=True)
                display(HTML('<p style="color:#94a3b8">No data for selected filters.</p>'))
        return

    #  Trend charts
    yr_grp = f.groupby("Year").size().reset_index(name="Accidents")
    fat_gr = f.groupby("Year")["Fatalities"].sum().reset_index()

    fig_trend = make_subplots(rows=1, cols=2,
        subplot_titles=("Accidents per Year", "Fatalities per Year"))
    fig_trend.add_trace(go.Scatter(
        x=yr_grp.Year, y=yr_grp.Accidents, mode="lines",
        line=dict(color=ACCENT, width=2), name="Accidents"), 1,1)
    fig_trend.add_trace(go.Scatter(
        x=fat_gr.Year, y=fat_gr.Fatalities, fill="tozeroy",
        line=dict(color=WARN), fillcolor="rgba(249,115,22,.2)",
        name="Fatalities"), 1,2)
    fig_trend.update_layout(**PLOT_KW, height=350, showlegend=False, # Increased height
        annotations=[dict(font=dict(color="#cbd5e1",size=11))for a in fig_trend.layout.annotations])
    for ann in fig_trend.layout.annotations:
        ann.font = dict(color="#cbd5e1", size=12)

    with out_trend:
        out_trend.clear_output(wait=True)
        fig_trend.show()

    # Decade + Cause pie
    dec = f.groupby("DecadeLabel").agg(
        Accidents=("Year","count"), Fatalities=("Fatalities","sum")
    ).reset_index()
    cs  = f.CauseCategory.value_counts().reset_index()
    cs.columns = ["Cause","Count"]

    fig_mid = make_subplots(rows=1, cols=2,
        specs=[[{"type":"bar"},{"type":"domain"}]],
        subplot_titles=("Decade-wise Profile", "Cause Breakdown"))
    fig_mid.add_trace(go.Bar(
        x=dec.DecadeLabel, y=dec.Accidents,
        marker=dict(color=dec.Fatalities, colorscale="Turbo", showscale=False),
        name="Accidents"), 1,1)
    fig_mid.add_trace(go.Pie(
        labels=cs.Cause, values=cs.Count, hole=.52,
        marker=dict(colors=px.colors.sequential.Plasma_r),
        textfont=dict(size=10)), 1,2)
    fig_mid.update_layout(**PLOT_KW, height=380, showlegend=True, # Increased height
        legend=dict(font=dict(size=9), x=1.02, y=0.8, xanchor='left', yanchor='top')) # Moved legend outside
    for ann in fig_mid.layout.annotations:
        ann.font = dict(color="#cbd5e1", size=12)

    with out_mid:
        out_mid.clear_output(wait=True)
        fig_mid.show()

    # Countries + Manufacturers
    ctry = f.Country.value_counts().head(12).reset_index()
    ctry.columns = ["Country","Accidents"]
    mfg  = f.Manufacturer.value_counts().head(10).reset_index()
    mfg.columns  = ["Manufacturer","Accidents"]

    fig_geo = make_subplots(rows=1, cols=2,
        subplot_titles=("Top Countries by Accidents", "Top Manufacturers"))
    fig_geo.add_trace(go.Bar(
        x=ctry.Accidents, y=ctry.Country, orientation="h",
        marker=dict(color=ctry.Accidents, colorscale="Cividis"),
        name="Countries"), 1,1)
    fig_geo.add_trace(go.Bar(
        x=mfg.Accidents, y=mfg.Manufacturer, orientation="h", # Changed to horizontal bar chart
        marker=dict(color=mfg.Accidents, colorscale="Magma"),
        name="Manufacturers"), 1,2)
    fig_geo.update_yaxes(autorange="reversed", row=1, col=1)
    fig_geo.update_yaxes(autorange="reversed", row=1, col=2) # Reverse y-axis for the new horizontal bar chart
    fig_geo.update_layout(**PLOT_KW, height=450, showlegend=False) # Increased height
    for ann in fig_geo.layout.annotations:
        ann.font = dict(color="#cbd5e1", size=12)

    with out_geo:
        out_geo.clear_output(wait=True)
        fig_geo.show()

    # Seasonal
    month_names = ["Jan","Feb","Mar","Apr","May","Jun",
                   "Jul","Aug","Sep","Oct","Nov","Dec"]
    mo = (f.groupby("Month").size()
           .reindex(range(1,13), fill_value=0)
           .reset_index(name="Accidents"))
    mo["MonthName"] = month_names

    fig_sea = go.Figure(go.Bar(
        x=mo.MonthName, y=mo.Accidents,
        marker=dict(color=mo.Accidents, colorscale="Teal")))
    fig_sea.update_layout(**PLOT_KW, height=300, # Increased height
        title=dict(text="Seasonal Pattern (Accidents by Month)",
                   font=dict(color="#cbd5e1",size=12)))

    with out_season:
        out_season.clear_output(wait=True)
        fig_sea.show()

    #  Top 10 Table
    top10 = (f.nlargest(10,"Fatalities")
              [["Date","Operator","Location","Manufacturer",
                "Aboard","Fatalities","CauseCategory"]]
              .reset_index(drop=True))
    top10["Date"] = top10["Date"].dt.strftime("%Y-%m-%d")

    rows_html = "".join(
        f"""<tr>
          <td>{r.Date}</td><td>{r.Operator[:28]}</td>
          <td>{r.Location[:28]}</td><td>{r.Manufacturer}</td>
          <td style="color:{WARN};font-weight:600">{int(r.Fatalities)}</td>
          <td>{int(r.Aboard)}</td>
          <td style="color:{MUTED}">{r.CauseCategory}</td>
        </tr>""" for _, r in top10.iterrows()
    )
    table_html = f"""
    <div style="overflow-x:auto">
    <table style="width:100%;border-collapse:collapse;
                  font-size:12px;color:{TXT};">
      <thead><tr style="background:#1e293b;color:{MUTED};
                        text-transform:uppercase;font-size:10px;">
        <th style="padding:8px;text-align:left">Date</th>
        <th style="padding:8px;text-align:left">Operator</th>
        <th style="padding:8px;text-align:left">Location</th>
        <th style="padding:8px;text-align:left">Manufacturer</th>
        <th style="padding:8px;text-align:right">Fatalities</th>
        <th style="padding:8px;text-align:right">Aboard</th>
        <th style="padding:8px;text-align:left">Cause</th>
      </tr></thead>
      <tbody>
        {rows_html}
      </tbody>
    </table>
    </div>
    """
    with out_table:
        out_table.clear_output(wait=True)
        display(HTML(table_html))

for w in [w_year, w_op, w_cause, w_mfg]:
    w.observe(render, names="value")

display(HTML(f"""
<div class="dash-wrap">
  <p class="dash-title">✈️ Aviation Safety — Executive Dashboard</p>
  <p class="dash-sub">Global airplane accidents · {yr_min}–{yr_max} · {len(df):,} incidents</p>
</div>
"""))

# Filters box
filter_box = widgets.VBox([
    widgets.HTML('<div class="filter-lbl">🎛️ FILTERS — Select filters to update charts live</div>'),
    w_year,
    widgets.HBox([w_op, w_cause, w_mfg],
                 layout=widgets.Layout(gap="16px"))
], layout=widgets.Layout(
    background=PANEL,
    padding="14px",
    border="1px solid #1f2a44",
    border_radius="10px",
    margin="0 0 16px 0"
))

full_dashboard = widgets.VBox([
    filter_box,
    out_kpi,
    out_trend,
    out_mid,
    out_geo,
    out_season,
    widgets.HTML('<div class="section">🔴 Top 10 Deadliest Crashes (Filtered)</div>'),
    out_table,
])

display(full_dashboard)

# Initial render
render()
print("✅ Dashboard loaded — change filters to update charts live!")